# Generated by Django 5.2.4 on 2025-07-31 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recomendaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recomendaciones',
            table='recomendaciones',
        ),
    ]
