# Generated by Django 5.2.4 on 2025-07-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recomendaciones', '0002_alter_recomendaciones_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendaciones',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='recomendaciones',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='recomendaciones',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='recomendaciones',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='recomendaciones',
            name='titulo',
        ),
        migrations.AddField(
            model_name='recomendaciones',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
