# Generated by Django 5.2.4 on 2025-08-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'anuncios',
            },
        ),
    ]
