# Generated by Django 5.2.4 on 2025-08-01 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.PositiveIntegerField(blank=True, null=True)),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('type', models.SmallIntegerField(blank=True, choices=[(1, 'Evento'), (2, 'Descuento')], null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categoria')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producto')),
            ],
            options={
                'db_table': 'descuentostab',
            },
        ),
    ]
