# Generated by Django 5.2.4 on 2025-08-01 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('varietyOptions', models.JSONField(blank=True, null=True)),
                ('isActive', models.BooleanField(blank=True, null=True)),
                ('isFavorite', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categoria')),
            ],
        ),
    ]
